import NftItemCard from '@components/common/NftItemCard'
import { MediaRenderer, useNFTCollection, useNFTs } from '@thirdweb-dev/react'
import Head from 'next/head'
import InnerContainerLayout from '../components/layouts/InnerContainerLayout'
import MainLayout from '../components/layouts/MainLayout'

export default function HomePage() {
  const nftCollection = useNFTCollection(process.env.NEXT_PUBLIC_TEST_NFT_COLLECTION)
  const { data: nfts, isLoading, error } = useNFTs(nftCollection)

  return (
    <>
      <Head>
        <title>Marketplace NFT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <InnerContainerLayout className="py-6">
          <div className="mb-4">
            <h1 className="text-2xl font-bold">
              Boxing Collection
            </h1>
            <p className="">
              This collection has {nfts?.length} NFTs
            </p>
          </div>
          <ul className="grid grid-cols-3 gap-2">
            {nfts?.map((nft) => (
              <NftItemCard key={nft.metadata.uri} nft={nft} />
            ))}
          </ul>
        </InnerContainerLayout>
      </MainLayout>
    </>
  )
}
